:seedling: Compare current main with v1.1.x.

diff --git a/.github/workflows/pr-verify.yml b/.github/workflows/pr-verify.yml
--- a/.github/workflows/pr-verify.yml
+++ b/.github/workflows/pr-verify.yml
@@ -10,13 +10,26 @@ jobs:
       pull-requests: write
       issues: write
     runs-on: ubuntu-latest
+    container:
+      image: ghcr.io/syself/caph-builder:1.0.27
+      credentials:
+        username: ${{ github.actor }}
+        password: ${{ secrets.github_token }}
     name: Verify Pull Request
     steps:
       - name: Checkout repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
+      - name: Fix Env Var HOME
+        uses: ./.github/actions/fixes
+        # Fixes:
+        #   fatal: detected dubious ownership in repository at '/__w/clu...
+        #   To add an exception for this directory, call:
+        #   git config --global --add safe.directory /__w...
+
       # Take from https://github.com/kubernetes-sigs/kubebuilder/blob/master/.github/workflows/verify.yml
       - name: Validate PR Title Format
+        shell: bash
         env:
           TITLE: ${{ github.event.pull_request.title }}
         run: |
@@ -25,16 +38,15 @@ jobs:
             exit 1
           fi
 
-          if ! [[ "$TITLE" =~ ^($'\u26A0'|:warning:|$'\u2728'|:sparkles:|$'\U0001F41B'|:bug:|$'\U0001F4D6'|:book:|$'\U0001F680'|:release:|$'\U0001F331'|:seedling:) ]]; then
-            echo "Error: Invalid PR title format."
-            echo "Your PR title must start with one of the following indicators:"
-            echo "- Breaking change: ⚠ (U+26A0) or :warning:"
-            echo "- Non-breaking feature: ✨ (U+2728) or :sparkles:"
-            echo "- Patch fix: 🐛 (U+1F41B) or :bug:"
-            echo "- Docs: 📖 (U+1F4D6) or :book:"
-            echo "- Release: 🚀 (U+1F680) or :release:"
-            echo "- Infra/Tests/Other: 🌱 (U+1F331) or :seedling:"
-            exit 1
+          if ! [[ "$TITLE" =~ ^(⚠|:warning:|✨|:sparkles:|🐛|:bug:|📖|:book:|🚀|:release:|🌱|:seedling:) ]]; then
+              echo "Error: Invalid PR title format."
+              echo "Your PR title must start with one of the following indicators:"
+              echo "- Breaking change: ⚠ or :warning:"
+              echo "- Non-breaking feature: ✨ or :sparkles:"
+              echo "- Patch fix: 🐛 or :bug:"
+              echo "- Docs: 📖 or :book:"
+              echo "- Release: 🚀 or :release:"
+              echo "- Infra/Tests/Other: 🌱 (U+1F331) or :seedling:"
           fi
 
           echo "PR title is valid: '$TITLE'"
@@ -45,8 +57,21 @@ jobs:
       - name: Verify Shellcheck
         run: make verify-shellcheck
 
+      - name: Verify CAPI Version
+        run: make verify-capi-version
+
       - name: Verify Starlark
         run: make verify-starlark
+
+      - name: Verify Generated Files of Git Repo
+        env:
+          # Use dummy data.
+          HETZNER_ROBOT_USER: ${{ secrets.HETZNER_ROBOT_USER || 'robot' }}
+          HETZNER_ROBOT_PASSWORD: ${{ secrets.HETZNER_ROBOT_PASSWORD || 'password' }}
+          HETZNER_SSH_PUB: ${{ secrets.HETZNER_SSH_PUB || 'c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUZha2VQdWJsaWNLZXlGb3JDSU9ubHkgdXNlckBjaQ==' }}
+          HETZNER_SSH_PRIV: ${{ secrets.HETZNER_SSH_PRIV || 'LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KZmFrZQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K' }}
+          SSH_KEY_NAME: ${{ secrets.SSH_KEY_NAME || 'ci-key' }}
+        run: make verify-generated-files
 
       - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
         with:
@@ -55,6 +80,7 @@ jobs:
         run: npm i -g renovate@35.54.0 # TODO update this via renovatebot
 
       - name: Validate config
+        shell: bash
         run: |
           for file in $(find . -name "*.json5"); do
             renovate-config-validator ${file}
